FROM ubuntu:latest
MAINTAINER Jay Ridgeway <jayridge@gmail.com>

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get --fix-missing install -y git subversion wget build-essential binutils autoconf libtool pkg-config 

